CREATE TABLE IF NOT EXISTS `User` (
  `username` VARCHAR(100) PRIMARY KEY,
  `password` VARBINARY(256) NOT NULL,
  `idCoupon` VARCHAR(192) REFERENCES `Coupon`.`idCoupon`
);

CREATE TABLE IF NOT EXISTS `Coupon` (
  `idCoupon` VARCHAR(192) PRIMARY KEY,
  `value` INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS `Purchase` (
  `idPurchase` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL REFERENCES `User`.`username`,
  `value` INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS `Item` (
  `idItem` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `value` INT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS `Purchase_Item` (
  `idPurchase` INT UNSIGNED NOT NULL REFERENCES `Purchase`.`idPurchase`,
  `idItem` INT UNSIGNED NOT NULL REFERENCES `Item`.`idItem`,
  `amount` INT UNSIGNED NOT NULL,
  PRIMARY KEY(`idPurchase`, `idItem`)
);

CREATE TABLE IF NOT EXISTS `BlackListed_JWT` (`token` VARBINARY(1024) PRIMARY KEY)